image: php:7.0.30

test:
 script:
   - apt-get update -yqq
   - pecl install xdebug-2.4.0
   - docker-php-ext-enable xdebug
   - curl --location --output /usr/local/bin/phpdoc https://phpdoc.org/phpDocumentor.phar
   - chmod +x /usr/local/bin/phpdoc
   - curl --location --output /usr/local/bin/phpunit https://phar.phpunit.de/phpunit-6.5.9.phar
   - chmod +x /usr/local/bin/phpunit
   - docker-php-ext-install pdo_mysql
   - cd tests/
   - phpunit --coverage-html /builds/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME/tests/coverage/
   - phpdoc -d /builds/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME/ -t /builds/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME/doc/ --ignore vendor/,tests/,app/views/,logs/,public/,.idea/,docs/
 
 artifacts:
   paths:
     - /builds/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME/tests/coverage/
     - /builds/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME/doc/

pages:
 stage: deploy
 dependencies:
   - test
 script:
   - mv /builds/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME/tests/coverage/ public/
   - mv /builds/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME/doc/ public/
 artifacts:
   paths:
     - public
   expire_in: 30 days
