<?php
/**
 * Course Model Class File.
 * @author Mukarram Ishaq
 */
namespace App\Models;

use Core\Models\BaseModel;
use Core\Models\Database\DatabaseInterface;
/**
 * Class Course
 * @package App\Models
 */
class Course extends BaseModel
{

    /**
     * Course constructor.
     * @param DatabaseInterface $database
     */
    public function __construct(DatabaseInterface $database)
    {
        parent::__construct($database);
        $this->table = "courses";
        $this->loadClassPublicProperties();
    }

    /**
     * Course destructor.
     */
    public function __destruct()
    {
        parent::__destruct(); // TODO: Change the autogenerated stub
    }
}