<?php
/**
 * Student Model Class File.
 * @author Mukarram Ishaq
 */
namespace App\Models;

use Core\Models\BaseModel;
use Core\Models\Database\DatabaseInterface;
/**
 * Class Student
 * @package App\Models
 */
class Student extends BaseModel
{

    /**
     * Student constructor.
     * @param DatabaseInterface $database
     */
    public function __construct(DatabaseInterface $database)
    {
        parent::__construct($database);
        $this->table = "students";
        $this->loadClassPublicProperties();
    }

    /**
     * Student destructor.
     */
    public function __destruct()
    {
        parent::__destruct(); // TODO: Change the autogenerated stub
    }
}